(function ($) {
$.Redactor.opts.langs['pl'] = {
	html: 'Źródło',
	video: 'Wideo',
	image: 'Obrazek',
	table: 'Tabela',
	link: 'Link',
	link_insert: 'Wstaw link ...',
	link_edit: 'Edit link',
	unlink: 'Usuń link',
	formatting: 'Style',
	paragraph: 'Zwykły tekst',
	quote: 'Cytat',
	code: 'Kod źródłowy',
	header1: 'Nagłówek 1',
	header2: 'Nagłówek 2',
	header3: 'Nagłówek 3',
	header4: 'Nagłówek 4',
	header5: 'Nagłówek 5',
	bold:  'Pogrubiony',
	italic: 'Pochylony',
	fontcolor: 'Kolor tekstu',
	backcolor: 'Kolor tła',
	unorderedlist: 'Wypunktowanie',
	orderedlist: 'Numeracja',
	outdent: 'Zmniejsz wcięcie',
	indent: 'Zwiększ wcięcie',
	cancel: 'Anuluj',
	insert: 'Wstaw',
	save: 'Zachowaj',
	_delete: 'Usuń',
	insert_table: 'Wstaw tabele',
	insert_row_above: 'Dodaj wiersz na górze',
	insert_row_below: 'Dodaj wiersz na dole',
	insert_column_left: 'Dodaj kolumnę po lewej',
	insert_column_right: 'Dodaj kolumnę po prawej',
	delete_column: 'Usuń kolumnę',
	delete_row: 'Usuń wiersz',
	delete_table: 'Usuń tabele',
	rows: 'Wiersze',
	columns: 'Kolumny',
	add_head: 'Dodaj Nagłówek',
	delete_head: 'Usuń Nagłówek',
	title: 'Opis',
	image_position: 'Wyrównanie',
	none: 'nie ma',
	left: 'od lewej',
	right: 'od prawej',
	image_web_link: 'Link do obrazka',
	text: 'Tekst',
	mailto: 'Poczta e-mail',
	web: 'URL',
	video_html_code: 'Kod źródłowy pliku wideo',
	file: 'Plik (tylko .pdf, .doc, .docx)',
	upload: 'Wgraj na serwer (max. 500 kB)',
	download: 'Pobierz',
	choose: 'Wybierz z listy',
	or_choose: 'lub wybierz',
	drop_file_here: 'Przenieś plik tutaj ',
	align_left:	'Tekst do lewej',
	align_center: 'Wyśrodkuj',
	align_right: 'Tekst do prawej',
	align_justify: 'Wyjustuj',
	horizontalrule: 'Linia pozioma',
	fullscreen: 'Pełny ekran',
	deleted: 'Usunięty',
    anchor: 'Kotwica',
	link_new_tab: 'Otwórz link w nowym oknie',
	underline: 'Pokdreślony',
	alignment: 'Wyrównanie',
	filename: 'Nazwa ',
	edit: 'Edycja'
};
})( jQuery );
