(function ($) {
$.Redactor.opts.langs['pl'] = {
	html: '¬ród³o',
	video: 'Wideo',
	image: 'Obrazek',
	table: 'Tabela',
	link: 'Link',
	link_insert: 'Wstaw link ...',
	link_edit: 'Edit link',
	unlink: 'Usuñ link',
	formatting: 'Style',
	paragraph: 'Zwyk³y tekst',
	quote: 'Cytat',
	code: 'Kod ¼ród³owy',
	header1: 'Nag³ówek 1',
	header2: 'Nag³ówek 2',
	header3: 'Nag³ówek 3',
	header4: 'Nag³ówek 4',
	header5: 'Nag³ówek 5',
	bold:  'Pogrubiony',
	italic: 'Pochylony',
	fontcolor: 'Kolor tekstu',
	backcolor: 'Kolor t³a',
	unorderedlist: 'Wypunktowanie',
	orderedlist: 'Numeracja',
	outdent: 'Zmniejsz wciêcie',
	indent: 'Zwiêksz wciêcie',
	cancel: 'Anuluj',
	insert: 'Wstaw',
	save: 'Zachowaj',
	_delete: 'Usuñ',
	insert_table: 'Wstaw tabele',
	insert_row_above: 'Dodaj wiersz na górze',
	insert_row_below: 'Dodaj wiersz na dole',
	insert_column_left: 'Dodaj kolumnê po lewej',
	insert_column_right: 'Dodaj kolumnê po prawej',
	delete_column: 'Usuñ kolumnê',
	delete_row: 'Usuñ wiersz',
	delete_table: 'Usuñ tabele',
	rows: 'Wiersze',
	columns: 'Kolumny',
	add_head: 'Dodaj nag³ówek',
	delete_head: 'Usuñ nag³ówek',
	title: 'Opis',
	image_position: 'Wyrównanie',
	none: 'nie ma',
	left: 'od lewej',
	right: 'od prawej',
	image_web_link: 'Link do obrazka',
	text: 'Tekst',
	mailto: 'Poczta e-mail',
	web: 'URL',
	video_html_code: 'Kod ¼ród³owy pliku wideo',
	file: 'Plik (tylko .pdf, .doc, .docx)',
	upload: 'Wgraj na serwer (max. 500 kB)',
	download: 'Pobierz',
	choose: 'Wybierz z listy',
	or_choose: 'lub wybierz',
	drop_file_here: 'Przenie¶ plik tutaj ',
	align_left:	'Tekst do lewej',
	align_center: 'Wy¶rodkuj',
	align_right: 'Tekst do prawej',
	align_justify: 'Wyjustuj',
	horizontalrule: 'Linia pozioma',
	fullscreen: 'Pe³ny ekran',
	deleted: 'Usuniêty',
    anchor: 'Kotwica',
	link_new_tab: 'Otwórz link w nowym oknie',
	underline: 'Pokdre¶lony',
	alignment: 'Wyrównanie',
	filename: 'Nazwa ',
	edit: 'Edycja'
};
})( jQuery );
